workflows:
  expo-apk:
    name: Expo APK (no-wait)
    # Kort og robust: vi *triggrer* EAS-build og avslutter jobben raskt.
    environment:
      node: 20
      groups:
        - expo        # inneholder EXPO_TOKEN i Codemagic
    cache:
      cache_paths:
        - ~/.npm
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies (npm, tolerant)
        script: |
          echo "legacy-peer-deps=true" > .npmrc
          if [ -f package-lock.json ]; then
            npm ci --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi
      - name: Install EAS CLI and authenticate
        script: |
          npm i -g eas-cli
          eas whoami || eas login --token "$EXPO_TOKEN"
      - name: Trigger EAS build (do not wait) and print dashboard URL
        script: |
          URL=$(eas build -p android --profile preview --non-interactive --no-wait --json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const j=JSON.parse(s);const b=Array.isArray(j)?j[0]:j;console.log(b?.webUrl||b?.dashboardUrl||b?.buildUrl||'')});")
          echo "EAS build URL: $URL"
          mkdir -p artifacts
          echo "$URL" > artifacts/eas_build_url.txt
    artifacts:
      - artifacts/eas_build_url.txt
