workflows:
  expo-apk:
    name: Expo APK
    max_build_duration: 60
    instance_type: linux
    environment:
      node: 20
      groups:
        - expo        # <- dette er gruppa du laget med EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --legacy-peer-deps
          fi
      - name: Install EAS CLI and auth
        script: |
          npm i -g eas-cli
          eas whoami || eas login --token "$EXPO_TOKEN"
      - name: Build Android APK with EAS (preview profile)
        script: |
          eas build -p android --profile preview --non-interactive --json > build.json
      - name: Download APK artifact
        script: |
          mkdir -p artifacts
          node -e "const fs=require('fs'); const j=JSON.parse(fs.readFileSync('build.json','utf8')); const url=(j[0]?.artifacts?.applicationArchiveUrl)||(j[0]?.artifacts?.buildUrl)||(j.artifacts?.applicationArchiveUrl)||(j.artifacts?.buildUrl); if(!url){throw new Error('No APK URL');} console.log(url)" > apk_url.txt
          curl -L "$(cat apk_url.txt)" -o artifacts/app-preview.apk
    artifacts:
      - artifacts/*.apk
