workflows:
  expo-apk:
    name: Expo APK
    # Øk tidslimit fra 60 til 120 min
    max_build_duration: 120
    environment:
      node: 20
      groups:
        - expo
    cache:
      cache_paths:
        - ~/.npm
        - $CM_BUILD_DIR/node_modules
        scripts:
      - name: Install dependencies (npm)
        script: |
          echo "legacy-peer-deps=true" > .npmrc
          if [ -f package-lock.json ]; then
            npm ci --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi
      - name: Install EAS CLI and auth
        script: |
          npm i -g eas-cli
          eas whoami || eas login --token "$EXPO_TOKEN"
      - name: Trigger EAS build (no wait) and print URL
        script: |
          URL=$(eas build -p android --profile preview --non-interactive --no-wait --json | node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const j=JSON.parse(s);const b=Array.isArray(j)?j[0]:j;console.log(b?.webUrl||b?.dashboardUrl||b?.buildUrl||'');});")
          echo "EAS build URL: $URL"
          echo "$URL" > eas_build_url.txt
    artifacts:
      - artifacts/*.apk
