workflows:
  expo-apk:
    name: Expo APK
    # Øk tidslimit fra 60 til 120 min
    max_build_duration: 120
    environment:
      node: 20
      groups:
        - expo
    cache:
      cache_paths:
        - ~/.npm
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies (npm, stabil og rask)
        script: |
          echo "legacy-peer-deps=true" > .npmrc
          if [ -f package-lock.json ]; then
            npm ci --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi
      - name: Install EAS CLI and auth
        script: |
          npm i -g eas-cli
          eas whoami || eas login --token "$EXPO_TOKEN"
      - name: Build Android APK with EAS (preview profile)
        script: |
          eas build -p android --profile preview --non-interactive --json > build.json
      - name: Download APK artifact
        script: |
          mkdir -p artifacts
          node -e "const fs=require('fs'); const j=JSON.parse(fs.readFileSync('build.json','utf8')); const b=Array.isArray(j)?j[0]:j; const u=b?.artifacts?.applicationArchiveUrl||b?.artifacts?.buildUrl; if(!u){console.error(j); throw new Error('No APK URL');} console.log(u)" > apk_url.txt
          curl -L "$(cat apk_url.txt)" -o artifacts/app-preview.apk
    artifacts:
      - artifacts/*.apk
