workflows:
  android-debug-apk:
    name: Android Debug APK (no EAS)
    max_build_duration: 90
    environment:
      node: 20
      java: 17
      vars:
        EXPO_NO_TELEMETRY: "1"
    cache:
      cache_paths:
        - ~/.npm
        - $CM_BUILD_DIR/node_modules
        - $CM_BUILD_DIR/android/.gradle
        - ~/.gradle
    scripts:
      - name: Install JS deps
        script: |
          echo "legacy-peer-deps=true" > .npmrc
          if [ -f package-lock.json ]; then
            npm ci --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi
      - name: Prebuild native Android project
        script: |
          npx expo install || true
          npx expo prebuild --platform android --no-install --clean
      - name: Sync deps after prebuild
        script: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --fund=false
          else
            npm install --no-audit --fund=false
          fi
      - name: Build debug APK with Gradle
        script: |
          chmod +x android/gradlew
          cd android
          ./gradlew assembleDebug -x lint -x test
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
