workflows:
  android-release-apk:
    name: Android Release APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_APP_DIR: "android"
        ANDROID_MODULE: "app"
    scripts:
      - name: Gjenopprett keystore fra base64
        script: |
          echo "Restoring keystore to android/app/upload-keystore.jks"
          mkdir -p $CM_BUILD_DIR/android/app
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/upload-keystore.jks

      - name: Legg til signing-properties til Gradle
        script: |
          cat >> $CM_BUILD_DIR/android/gradle.properties <<EOF
          MYAPP_UPLOAD_STORE_FILE=upload-keystore.jks
          MYAPP_UPLOAD_KEY_ALIAS=$CM_KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=$CM_KEYSTORE_PASSWORD
          MYAPP_UPLOAD_KEY_PASSWORD=$CM_KEY_PASSWORD
          EOF
          echo "Signing properties appended to android/gradle.properties"

      - name: Bygg Release APK (signert)
        script: |
          cd android
          ./gradlew clean
          ./gradlew :app:assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
